### ISSUE TITLE
Install SB Admin 2 and build process

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/javascript#1]
See https://github.com/BlackrockDigital/startbootstrap-sb-admin-2

**Comment by deepiksdev** [comment]
@serverfire As discussed in private conversation, we have also chosen an open source template for the landing page:  http://tympanus.net/Freebies/Landio/ . Please also include it in the initial setup.

**Comment by deepiksdev** [comment]
@serverfire 

> As discussed in private conversation, we have also chosen an open source template for the landing page: http://tympanus.net/Freebies/Landio/ . Please also include it in the initial setup.

I realize this is already done! Thanks. Can we close this first issue?

**Comment by serverfire** [comment]
yes , it is done
